version: "3"
services:
  # app:
  #   build: 
  #     context: .
  #     dockerfile: LionchatBrain.Dockerfile
  #   links:
  #     - db
  #   ports:
  #     - "8000:8000"

  db:
    image: mysql:8.0.28
    ports:
      - "30000:3306"
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ml_database
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro