version: "3"
services:
  springfrontendbackend:
    build:
      context: .
      dockerfile: Lionchat.Dockerfile
    links:
      - pythonserver
    ports:
      - "8080:8080"

  pythonserver:
    build:
      context: ./pythonserver
      dockerfile: LionchatBrain.Dockerfile
    links:
      - db
    ports:
      - "8000:8000"

  db:
    image: mysql:8.0.28
    ports:
      - "30000:3306"
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ml_database
    volumes:
      - ./pythonserver/db:/docker-entrypoint-initdb.d/:ro
